### ISSUE TITLE
Project Details - Images not showing up

### ISSUE THREAD

**Issue by Sawrz** [devinsolutions/docker-taiga#6]
Hi,
thank you for maintaining the docker image. The installation process was a breeze =)

However, I ran lately into an issue:
I can change the logo in project details but the logo won't show up. Instead, I get the typical 'missing images icon'. I double checked this issue on taiga.io, where it doesn't happen for the same image.

The inspect tool tells me on my site the following:
log:
```
WebSocket connection to 'ws://127.0.0.1:8080/events' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
t.setupConnection @ app.js:3247
r @ lodash.js:4935
```

image:
`<img tg-project-logo-big-src="project._attrs" alt="logo" class="image" src="http://localhost:8080/media/project/2/a/f/2/fde42416853450ee23d74f43685ee45e61f5cdfc074b66c924b57eb3f4b0/phd_180.png.300x300_q85_crop.png" style="">`

I use a reverse proxy, which forwards the traffic to a dedicated URL. 

My docker compose file:
```
version: "3.7"

x-taiga-common: &taiga-common
  image: devinsolutions/taiga:latest
  volumes:
    - type: bind
      source: /share/cloud_services/taiga/media
      target: /srv/taiga-back/media
    - /share/Containers/config_templates/taiga/front.json:/etc/opt/taiga-front/conf.json:ro
    - /share/Containers/config_templates/taiga/settings.py:/etc/opt/taiga-back/settings.py:ro
services:

  broker:
    image: rabbitmq:3.7
    environment:
      RABBITMQ_DEFAULT_VHOST: taiga
      RABBITMQ_NODENAME: rabbit@localhost
    volumes:
      - broker:/var/lib/rabbitmq
    networks:
      - backend

  database:
    image: postgres:11
    environment:
      POSTGRES_DB: taiga
      POSTGRES_PASSWORD: MY_SUPER_SECRET_PASSWORD
      POSTGRES_USER: taiga
    stop_signal: SIGINT
    volumes:
      - type: bind
        source: /share/cloud_services/taiga/db
        target: /var/lib/postgresql/data
    networks:
      - backend

  events:
    image: devinsolutions/taiga-events:latest
    deploy:
      replicas: 1
      update_config:
        order: start-first
    healthcheck:
      interval: 5s
      # Taiga-events seems unable to reconnect to message broker when connection cannot be
      # established or is closed. There also does not seem to be another way to tell if the server
      # is actually able to communicate with the broker.
      test: "wget -q -t 1 http://localhost:8080 2>&1 | grep -q '426 Upgrade Required' &&
        ! egrep -m 1 -q '^Unhandled rejection ' /var/log/taiga-events.log"
    volumes:
      - /share/Containers/config_templates/taiga/events.json:/etc/opt/taiga-events/config.json:ro
    networks:
      - backend

  migrations:
    <<: *taiga-common
    command:
      - migrate
      # Make sure this command is run only during the initial setup as it will
      # overwrite existing data.
      # - populate-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - backend

  reverse-proxy:
    image: nginx:1.17
    #ports:
    #  - "9187:80"
    stop_signal: SIGQUIT
    volumes:
      - /share/Containers/config_templates/taiga/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - backend
      - reverse_proxy
    environment:
      - VIRTUAL_HOST=MY_URL
      - LETSENCRYPT_HOST=MY_URL

  server:
    <<: *taiga-common
    command: run-server
    deploy:
      replicas: 1
      update_config:
        order: start-first
    environment:
      UWSGI_HTTP: ~
      UWSGI_HTTP_SOCKET: :8080
      UWSGI_OFFLOAD_THREADS: 4
      UWSGI_UWSGI_SOCKET: :3031
    healthcheck:
      test: wget -q -t 1 --spider http://localhost:8080/api/v1/
    stop_signal: SIGHUP
    networks:
      - backend

volumes:
  broker:

networks:
  backend:
    name: taiga_backend
  reverse_proxy:
    external: true
```

My default.conf:
```
server {
    listen 80 default_server;
    server_name _;

    charset utf-8;
    client_max_body_size 50M;
    large_client_header_buffers 4 32k;
    resolver 127.0.0.11 valid=0s;

    location / {
        set $upstream_server server;
        uwsgi_pass $upstream_server:3031;
        include uwsgi_params;
    }

    location /events {
        set $upstream_events events;
        proxy_pass http://$upstream_events:8080/events;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 7d;
        proxy_read_timeout 7d;
        proxy_send_timeout 7d;
    }
}
```

My front.json (i assume the culprit will be somewhere here...):
```
{
    "api": "/api/v1/",
    "eventsUrl": "ws://127.0.0.1:8080/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "supportUrl": "https://tree.taiga.io/support/",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "GDPRUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "tribeHost": null,
    "importers": [],
    "gravatar": true,
    "rtlLanguages": ["fa"]
}
```

My events.json:
```
{
    "url": "amqp://guest:guest@broker/taiga",
    "secret": "<secret key>",
    "webSocketServer": {
        "port": 8080
    }
}
```

My settings.py:
```
SECRET_KEY = '<secret key>'
PUBLIC_REGISTER_ENABLED = False

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'MY_URL'
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'taiga',
        'USER': 'taiga',
        'PASSWORD': 'MY_SUPER_SECRET_PASSWORD',
        'HOST': 'database',
        'PORT': '5432',
    }
}

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://guest:guest@broker/taiga"}
```

Do you have any idea what's wrong here?

Thank you in advance!

Cheers,
Sandro

**Comment by lubo** [comment]
>Hi,
>thank you for maintaining the docker image. The installation process was a breeze =)

Hi. You're welcome and I'm glad to hear that. :) 

>However, I ran lately into an issue:
>I can change the logo in project details but the logo won't show up. Instead, I get the typical 'missing images icon'. I double checked this issue on taiga.io, where it doesn't happen for the same image.

Is `/share/cloud_services/taiga/media` writable by UID `101`? When you bind-mount a directory, the permissions in the container are the same as on the host. Take a look at the directory, the image is probably not there.

>```
>WebSocket connection to 'ws://127.0.0.1:8080/events' failed: Error in connection establishment: >net::ERR_CONNECTION_REFUSED
>t.setupConnection @ app.js:3247
>r @ lodash.js:4935
>```

Is `127.0.0.1:8080` the correct address of your front-facing reverse proxy? Is your your front-facing reverse proxy configured properly? Keep in mind that `Connection` and `Upgrade` are hop-by-hop headers and therefore must be explicitly passed with each hop.

I'm closing this issue because you haven't provided evidence that there's a problem in this image and I'll reopen it if you do.

**Comment by Sawrz** [comment]
> Is `/share/cloud_services/taiga/media` writable by UID `101`? When you bind-mount a directory, the permissions in the container are the same as on the host. Take a look at the directory, the image is probably not there.

Yes it's writable. When I upload the picture it shows up in my folders. I was able to open the automatically cropped pictures too. That part should be fine, I guess. 

> Is 127.0.0.1:8080 the correct address of your front-facing reverse proxy? Is your your front-facing reverse proxy configured properly? Keep in mind that Connection and Upgrade are hop-by-hop headers and therefore must be explicitly passed with each hop.

Here I'm not sure what you're saying. I assume you suspect a configured my reverse proxy wrong. My reverse proxy comes from another docker container based on that image https://github.com/jwilder/nginx-proxy. If you take a look at the docker-compse file, there are some environment variables with the given URLs. The configuration happens completely automatically within the other container. 
I assume the configuration of my reverse proxy is fine, since I can use taiga completely using my URL. I already created and populated scrum and kanban boards. No errors here. I don't get the given errors either as long I keep the default image. 

Since I didn't changed much of your docker-compose.advanced.yaml and that seems to use port 80, I assumed I can hand it over to my outer proxy which uses port 443. Are my assumptions wrong?

What confuses me, is that I get a malfunction only with that small feature. Everything else works fine...

Cheers,
Sandro

**Comment by lubo** [comment]
>Yes it's writable. When I upload the picture it shows up in my folders. I was able to open the automatically cropped pictures too. That part should be fine, I guess.

Perhaps I don't understand what the real problem is here. Do you get 404 when trying to access the image? I've just tried uploading a project logo on our production instance and it works as expected.

>Here I'm not sure what you're saying. I assume you suspect a configured my reverse proxy wrong. My reverse proxy comes from another docker container based on that image https://github.com/jwilder/nginx-proxy. If you take a look at the docker-compse file, there are some environment variables with the given URLs. The configuration happens completely automatically within the other container.
I assume the configuration of my reverse proxy is fine, since I can use taiga completely using my URL. I already created and populated scrum and kanban boards. No errors here. I don't get the given errors either as long I keep the default image.
>
>Since I didn't changed much of your docker-compose.advanced.yaml and that seems to use port 80, I assumed I can hand it over to my outer proxy which uses port 443. Are my assumptions wrong?

Only the websocket requires `Connection: upgrade` and `Upgrade: websocket`, everything else will work just fine without it. By default, Nginx overrides `Connection` header value with `close`, so if you haven't configured the proxy to pass these headers, then it's probably misconfigured. Btw, you don't need `reverse-proxy` if there's another front-facing reverse proxy.

>What confuses me, is that I get a malfunction only with that small feature. Everything else works fine…

Are you referring to the missing image or the websocket? Either way, it looks like you've misconfigured something.

**Comment by Sawrz** [comment]
> Perhaps I don't understand what the real problem is here. Do you get 404 when trying to access the image? I've just tried uploading a project logo on our production instance and it works as expected.

Maybe I wasn't clear about my problem. Sorry. When I change the project logo I get this:
http://i.imgur.com/MH9vewc.png

It's true for profile pictures as well. No I din't configured any proxy to pass headers. I'll have to take a look into that. 

> Btw, you don't need `reverse-proxy` if there's another front-facing reverse proxy.

Good to know. So just for me so I won't mess up:
I completely delete the reverse proxy service with default.conf and migrate the environment VIRTUAL_HOST and LETSENCRYPT_HOST to the server service?

Thank you so much for your patience! 

Cheers,
Sandro

**Comment by lubo** [comment]
>Maybe I wasn't clear about my problem. Sorry. When I change the project logo I get this:
http://i.imgur.com/MH9vewc.png

Okay, but do you get 404 or what? There're multiple reasons why this may not work.

>Good to know. So just for me so I won't mess up:
I completely delete the reverse proxy service with default.conf and migrate the environment VIRTUAL_HOST and LETSENCRYPT_HOST to the server service?

Yes, just remove `reverse-proxy` service and `default.conf`. This image doesn't use `LETSENCRYPT_HOST` and `VIRTUAL_HOST`.

**Comment by Sawrz** [comment]
> Yes, just remove `reverse-proxy` service and `default.conf`. This image doesn't use `LETSENCRYPT_HOST` and `VIRTUAL_HOST`.

Done and works like a charm. Thanks =)



> Okay, but do you get 404 or what? There're multiple reasons why this may not work.

Well that's an interesting one. If I copy the image URL I get the following:
http://localhost:8080/media/project/1/8/9/4/f6f4f5dc848145caf6607961d3ae38f3d22284220ba57a30b83f8f86031c/phd_300.png.300x300_q85_crop.png

I get site not reached error. Which makes sense. 

If I replace localhost:8080 with mu URL, so to say https://URL/media/project/1/8/9/4/f6f4f5dc848145caf6607961d3ae38f3d22284220ba57a30b83f8f86031c/phd_300.png.300x300_q85_crop.png

I see the image without any issue...

It seems, the mapping inside the container doesn't work. I had a similar issue with gitlab some time ago. The solution was to set an environment variable which replaces localhost entries with the given URL. But if it works in your instance, I had something misconfigured... 

Thank your for taking the time to troubleshoot with me!

**Comment by lubo** [comment]
Oh, I thought you use Taiga from localhost! If you take a look at [settings.py](https://github.com/devinsolutions/docker-taiga/blob/master/root/etc/opt/taiga-back/settings.py), you'll see you will have to change several settings, including `MEDIA_URL`, `STATIC_URL` and `SITES`. Also, change `eventsUrl` in `conf.json` and the websocket should start working.

I thought it's pretty obvious that these need to be changed.

**Comment by Sawrz** [comment]
> I thought it's pretty obvious that these need to be changed.

Are we talking about the same settings.py? I used the one you provided in the docker compose folder: https://github.com/devinsolutions/docker-taiga/blob/master/docker-compose/settings.py
I don't see any variables like `MEDIA_URL`, `STATIC_URL` and `SITES`. But now if you mention it, my rudimentary Django knowledge comes back a bit.

**Comment by lubo** [comment]
The `settings.py` I've linked previously is used as the default `/etc/opt/taiga-back/settings.py`. `docker-compose/settings.py` should be used for demonstration purposes only. Did you actually read [Configuring taiga-back](https://github.com/devinsolutions/docker-taiga#configuring-taiga-back)?

**Comment by Sawrz** [comment]
Well, I read that one for sure. But somehow I ignored the path leading to settings.py. That's a bit unfortunate. Maybe it's a good idea to add an additional sentence, stating that `docker-compose/settings.py` should be used for demonstration purposes only.

It's for sure my fault of comprehending half the information but since the yaml uses the settings.py, which is for demonstration purposes only, was a bit misleading. Alternatively you could add the comment there or merge both files. 

I assumed too much and didn't read the README good enough. No excuses here but maybe it saves you time if another one assumes too much =)

For my part: I'll go over every step I made there and try to fix my issue.

Thank you again for your time!

**Comment by Sawrz** [comment]
@lubo the pictures are working fine now. However, I still get a websocket error. However, this time Error code 200. 
I changed in front.json to
```
{
    "api": "https://URL/api/v1/",
    "eventsUrl": "events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "defaultLoginEnabled": true,
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "supportUrl": "https://tree.taiga.io/support/",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "GDPRUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "tribeHost": null,
    "importers": [],
    "gravatar": true,
    "rtlLanguages": ["fa"]
}
```

I found the exact same error [here](https://github.com/taigaio/taiga-events/issues/4). I use the same events.json and EVENTS_PUSH_BACKEND_OPTIONS you provided. Can you verify if you have the same issue on your dockers?

**Comment by lubo** [comment]
Your `eventsUrl` is wrong. You'll have to set it to `wss://URL/events`.

**Comment by Sawrz** [comment]
Thanks for your reply. Still getting the same handshake error....

Did I made here something wrong?
```
SITES = {
    "api": {
       "scheme": "https",
       "domain": "URL",
       "name": "api"
    },
    "front": {
       "scheme": "https",
       "domain": "URL",
       "name": "front"
    },
}

#SITE_ID = "api"
```

**Comment by lubo** [comment]
Again, is your proxy configured correctly? Does taiga-events receive `Connection: upgrade` and `Upgrade: websocket`?

**Comment by Sawrz** [comment]
Some snippets from my nginx.conf

```
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any                                                                                                                                                                                                                    
# Connection header that may have been passed to this server                                                                                                                                                                                                                                   
map $http_upgrade $proxy_connection {                                                                                                                                                                                                                                                          
  default upgrade;                                                                                                                                                                                                                                                                             
  '' close;                                                                                                                                                                                                                                                                                    
}
```
and
```
# HTTP 1.1 support                                                                                                                                                                                                                                                                             
proxy_http_version 1.1;                                                                                                                                                                                                                                                                        
proxy_buffering off;                                                                                                                                                                                                                                                                           
proxy_set_header Host $http_host;                                                                                                                                                                                                                                                              
proxy_set_header Upgrade $http_upgrade;                                                                                                                                                                                                                                                        
proxy_set_header Connection $proxy_connection;
```

So it looks fine...

Update:
@lubo I set the Connection header explicitly to upgrade and Upgrade to websocket to avoid complications. Still the same problem.

**Comment by lubo** [comment]
Unfortunately, I don't know where the problem is and at this point, it's out of scope of this forum. Let me know if you find a problem it the image itself or in the demo configuration.

**Comment by Sawrz** [comment]
Hi,
I'm dedicating now some time to fix this issue on my server. According to the [official documentation](https://taigaio.github.io/taiga-doc/dist/setup-production.html) in section 4.1 it says to run the following commands:
```
workon taiga
python manage.py runserver
```
I skip that part because I assume the server runs already (the log and connection via browser tell me it does).
Running those two commands, the documentation tells me I can reach `http://localhost:8000/api/v1/ `. Since the configs seem to run on port `8080`, I try to `wget` in the docker "server" container `http://localhost:8080/api/v1/`.
I get the following:
```
Connecting to localhost:8080 (127.0.0.1:8080)
wget: can't open 'index.html': Permission denied
```

Weirdly the health check runs fine! So, I'm really confused about what happens here. I access the container via `sh` as user taiga and root. Both tell me, I have no permission! I don't know if it's somehow related to the issue with the WebSocket.

Another behavior, I find weird is the fact that if I change 
```
"api": "https://<URL>/api/v1/",
"eventsUrl": "wss://<URL>/events",
```
to
```
"api": "http://localhost:8080/api/v1/",
"eventsUrl": "ws://localhost:8080/events",
```
I get error messages as follows:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/api/v1/issues?assigned_to=5&status__is_closed=false. (Reason: CORS request did not succeed).
```
I assumed it would work since the APIs address is `localhost:8080/api/v1`, but it seems it doesn't work.

I still run a reverse proxy, but instead of Nginx, I run Traefik (more info in docker.compose.yaml).

My configurations:
docker-compose.yaml
```
version: "3.7"

x-taiga-common: &taiga-common
  image: devinsolutions/taiga:${TAIGA_VERSION}
  volumes:
    - type: bind
      target: /srv/taiga-back/media
      source: ${ROOT_DIR}/media
    - type: bind
      target: /etc/opt/taiga-back/settings.py 
      source: ${ROOT_DIR}/config/settings.py
      read_only: true
    - type: bind
      target: /etc/opt/taiga-front/conf.json 
      source: ${ROOT_DIR}/config/front.json
      read_only: true

services:
  broker:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: taiga_broker
    environment:
      RABBITMQ_DEFAULT_VHOST: taiga
      RABBITMQ_NODENAME: rabbit@localhost
    volumes:
      - type: volume 
        target: /var/lib/rabbitmq 
        source: broker  
    networks:
      - backend

  database:
    image: postgres:${POSTGRES_VERSION}
    container_name: taiga_db
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD} 
    stop_signal: SIGINT
    volumes:
      - type: bind
        target: /var/lib/postgresql/data
        source: ${ROOT_DIR}/db
    networks:
      - backend

  events:
    image: devinsolutions/taiga-events:latest
    container_name: taiga_events
    deploy:
      replicas: 1
      update_config:
        order: start-first
    healthcheck:
      interval: 5s
      # Taiga-events seems unable to reconnect to message broker when connection cannot be
      # established or is closed. There also does not seem to be another way to tell if the server
      # is actually able to communicate with the broker.
      test: "wget -q -t 1 http://localhost:8080 2>&1 | grep -q '426 Upgrade Required' &&
        ! egrep -m 1 -q '^Unhandled rejection ' /var/log/taiga-events.log"
    volumes:
    - type: bind
      target: /etc/opt/taiga-events/config.json 
      source: ${ROOT_DIR}/config/events.json
      read_only: true
    networks:
      - backend

  migrations:
    <<: *taiga-common
    container_name: taiga_migrate
    command:
      - migrate
      # Make sure this command is run only during the initial setup as it will
      # overwrite existing data.
      # - populate-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - backend

  server:
    <<: *taiga-common
    container_name: taiga_server
    command: run-server
    deploy:
      replicas: 1
      update_config:
        order: start-first
    environment:
      UWSGI_HTTP: ~
      UWSGI_HTTP_SOCKET: :8080
      UWSGI_OFFLOAD_THREADS: 4
      UWSGI_UWSGI_SOCKET: :3031
    healthcheck:
      test: wget -q -t 1 --spider http://localhost:8080/api/v1/
    stop_signal: SIGHUP
    labels:
      # Reverse proxy and certificate
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.taiga.tls.certresolver=myresolver"
      # Website Configuration
      - "traefik.http.routers.taiga.entrypoints=websecure"
      - "traefik.http.routers.taiga.rule=Host(`${URL}`)"
      - "traefik.http.services.taiga.loadbalancer.server.port=8080"
    networks:
      - backend
      - reverse-proxy

volumes:
  broker:
    name: taiga-broker_data
    external: true

networks:
  backend:
    name: taiga
    external: true
  reverse-proxy:
    external: true
```

settings.py
```
# For the complete list of possible settings and their documentation, see
# https://docs.djangoproject.com/en/1.11/ref/settings/ and
# https://github.com/taigaio/taiga-back/tree/stable/settings. Documentation for
# custom Taiga settings can be found at https://taigaio.github.io/taiga-doc/dist/.
# Make sure to read https://docs.djangoproject.com/en/1.11/topics/security/ to
# learn how to secure your deployment.

#########################################
## GENERIC
#########################################

ALLOWED_HOSTS = [
    'localhost',
    '<URL>',
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'taiga',
        'USER': 'taiga',
        'PASSWORD': '<REDACTED>',
        'HOST': 'taiga_db',
        'PORT': '5432',
    }
}

MEDIA_URL = "https://<URL>/media/"
STATIC_URL = "https://<URL>/static/"

SECRET_KEY = '<REDACTED>'

SITES = {
    "api": {
       "scheme": "http",
       "domain": "localhost:8080",
       "name": "api"
    },
    "front": {
       "scheme": "http",
       "domain": "localhost:8080",
       "name": "front"
    },
}

#########################################
## REGISTRATION
#########################################

PUBLIC_REGISTER_ENABLED = False



SECURE_SSL_REDIRECT = False 
SESSION_COOKIE_SECURE = True
EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://guest:guest@taiga_broker/taiga"}
```

front.json
```
{
    "api": "https://<URL>/api/v1/",
    "eventsUrl": "wss://<URL>/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "defaultLoginEnabled": true,
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "supportUrl": "https://tree.taiga.io/support/",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "GDPRUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "tribeHost": null,
    "importers": [],
    "gravatar": true,
    "rtlLanguages": ["fa"]
}
```

events.json
```
{
    "url": "amqp://guest:guest@taiga_broker/taiga",
    "secret": "<REDACTED>",
    "webSocketServer": {
        "port": 8080
    }
}
```
There might be a configuration error on my end. However, I'm not able to tell since I don't have full knowledge of how exactly the image works; neither am I a web developer.
So, I try to investigate that error as much as I can on my own. However, some input would be very appreciated =)

Maybe it's an issue somebody will stumble upon at some point, or it's an issue within the image.

Thanks,
Sandro
