### ISSUE TITLE
Permission denied [core/socket.c line 230]

### ISSUE THREAD

**Issue by Sawrz** [devinsolutions/docker-taiga#8]
Hi,
I have an issue starting the latest taiga build on docker with Ubuntu Server 18.04.

The taiga_server shuts permanently down with the following error message:
`bind(): Permission denied [core/socket.c line 230]`

You linked to the USWGI documentation page, so I copied your ini and tried to set the socket manually, but the problem still exists. Some posts suggest to move the socket to /tmp but yet the same issue.

My USWGI environmental variables are set according to the compose file you provide:

```
UWSGI_HTTP = ~
UWSGI_HTTP_SOCKET = 8080
UWSGI_OFFLOAD_THREADS = 4
UWSGI_UWSGI_SOCKET = 3031
```

It's a permission problem for sure, but the container shuts down before I'm able to login to check some permissions.

Do you have any ideas?

Best,
Sandro

P.S. The full log is here

```Post-processed 'img/emojis/satisfied.png' as 'img/emojis/satisfied.0215e13f0ce1.png',
Post-processed 'img/emojis/page_facing_up.png' as 'img/emojis/page_facing_up.badfd4374777.png',
Post-processed 'img/emojis/last_quarter_moon.png' as 'img/emojis/last_quarter_moon.113eee6c339a.png',
Post-processed 'img/emojis/cry.png' as 'img/emojis/cry.066f0a8e8007.png',
Post-processed 'img/emojis/bride_with_veil.png' as 'img/emojis/bride_with_veil.479589c75ef7.png',
Post-processed 'img/emojis/+1.png' as 'img/emojis/+1.1265e19214d7.png',
Post-processed 'img/emojis/bow.png' as 'img/emojis/bow.359171114114.png',
Post-processed 'img/emojis/repeat_one.png' as 'img/emojis/repeat_one.f90e83153756.png',
Post-processed 'img/emojis/suspect.png' as 'img/emojis/suspect.a358405d03a8.png',
Post-processed 'img/emojis/flags.png' as 'img/emojis/flags.4035d7f64a33.png',
Post-processed 'img/emojis/full_moon.png' as 'img/emojis/full_moon.28d128a7ecf0.png',
Post-processed 'img/emojis/grapes.png' as 'img/emojis/grapes.ae15bf11a8e5.png',
Post-processed 'img/emojis/squirrel.png' as 'img/emojis/squirrel.953181108406.png',
Post-processed 'img/emojis/person_with_blond_hair.png' as 'img/emojis/person_with_blond_hair.6311643e3030.png',
Post-processed 'img/emojis/hibiscus.png' as 'img/emojis/hibiscus.6f8b58bbdda6.png',
Post-processed 'img/emojis/japan.png' as 'img/emojis/japan.2c12e9d07818.png',
Post-processed 'img/emojis/kr.png' as 'img/emojis/kr.a7ce8fbc4938.png',
Post-processed 'img/emojis/earth_africa.png' as 'img/emojis/earth_africa.b9fbdb7424c9.png',
Post-processed 'img/emojis/umbrella.png' as 'img/emojis/umbrella.4c1ce20c95a6.png',
Post-processed 'img/emojis/rocket.png' as 'img/emojis/rocket.95e468d6ef70.png',
Post-processed 'img/emojis/maple_leaf.png' as 'img/emojis/maple_leaf.b02a511bb0d9.png',
Post-processed 'img/emojis/no_mobile_phones.png' as 'img/emojis/no_mobile_phones.e96a32aa5ed2.png',
Post-processed 'emails/logo-web.png' as 'emails/logo-web.5589906ac9dc.png',
Post-processed 'emails/logo-twitter.png' as 'emails/logo-twitter.36870cca84d9.png',
Post-processed 'emails/top-bg-update.png' as 'emails/top-bg-update.ecc2bd74400e.png',
Post-processed 'emails/logo.png' as 'emails/logo.4db5dc4e03fb.png',
Post-processed 'emails/logo-color.png' as 'emails/logo-color.7dd421a9b797.png',
Post-processed 'emails/top-bg-hero.png' as 'emails/top-bg-hero.62b5908dae16.png',
Post-processed 'emails/logo-github.png' as 'emails/logo-github.d1f4495235c7.png',
Post-processed 'img/user-noimage.png' as 'img/user-noimage.5ce8fcc7f0e7.png',
Post-processed 'admin/css/base.css' as 'admin/css/base.6b517d0d5813.css',
Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.7ac78187c567.css',
Post-processed 'admin/css/forms.css' as 'admin/css/forms.2003a066ae02.css',
Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.4c867197b256.css',
Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css',
Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.f6dc691f8d62.css',
Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.494e4ec545c9.css',
Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.5e372b41c483.css',
Post-processed 'admin/css/base.css' as 'admin/css/base.6b517d0d5813.css',
Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.7ac78187c567.css',
Post-processed 'admin/css/forms.css' as 'admin/css/forms.2003a066ae02.css',
Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.4c867197b256.css',
Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css',
Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.f6dc691f8d62.css',
Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.494e4ec545c9.css',
Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.5e372b41c483.css',
,
941 static files copied to '/srv/taiga-back/static', 957 post-processed.,
[uWSGI] getting INI configuration from /usr/local/etc/uwsgi/uwsgi.ini,
*** Starting uWSGI 2.0.18 (64bit) on [Fri Apr 17 12:30:42 2020] ***,
compiled with version: 9.2.0 on 24 March 2020 11:05:59,
os: Linux-4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020,
nodename: 3740ddf5b593,
machine: x86_64,
clock source: unix,
pcre jit disabled,
detected number of CPU cores: 12,
current working directory: /opt/taiga-back,
detected binary path: /usr/local/bin/uwsgi,
*** dumping internal routing table ***,
[rule: 0] subject: path_info regexp: ^/favicon.ico$ action: goto:404,
[rule: 1] action: addheader:X-Content-Type-Options: nosniff,
[rule: 2] subject: path_info regexp: ^/((images|v-\d+)(/|$)|(conf.json|humans.txt|robots.txt)$) action: goto:front,
[rule: 3] subject: path_info regexp: ^/media(/|$) action: goto:media,
[rule: 4] subject: path_info regexp: ^/static(/|$) action: goto:static,
[rule: 5] action: addheader:X-Frame-Options: DENY,
[rule: 6] action: addheader:X-XSS-Protection: 1; mode=block,
[rule: 7] subject: path_info regexp: ^/(?!(admin|api)(/|$)) action: addheader:Cache-Control: no-cache, must-revalidate,
[rule: 8] subject: path_info regexp: ^/(?!(admin|api)(/|$)) action: static:/opt/taiga-front/index.html,
[rule: 9] action: last:,
[rule: 10] label: front,
[rule: 11] subject: path_info regexp: ^/(.*) action: rewrite:$1,
[rule: 12] subject: /opt/taiga-front/${PATH_INFO} func: isfile action: goto:front-file,
[rule: 13] action: goto:404,
[rule: 14] label: front-file,
[rule: 15] subject: path_info regexp: ^v-\d+/ action: addheader:Cache-Control: public, max-age=31536000,
[rule: 16] subject: path_info regexp: ^(?!v-\d+/) action: addheader:Cache-Control: no-cache, must-revalidate,
[rule: 17] action: static:/opt/taiga-front/${PATH_INFO},
[rule: 18] label: media,
[rule: 19] subject: path_info regexp: ^/media/(.*) action: rewrite:$1,
[rule: 20] subject: /srv/taiga-back/media/${PATH_INFO} func: isfile action: static:/srv/taiga-back/media/${PATH_INFO},
[rule: 21] action: goto:404,
[rule: 22] label: static,
[rule: 23] subject: path_info regexp: ^/static/(.*) action: rewrite:$1,
[rule: 24] subject: /srv/taiga-back/static/${PATH_INFO} func: isfile action: goto:static-file,
[rule: 25] action: goto:404,
[rule: 26] label: static-file,
[rule: 27] action: addheader:Cache-Control: public, max-age=31536000,
[rule: 28] action: static:/srv/taiga-back/static/${PATH_INFO},
[rule: 29] label: 404,
[rule: 30] action: addheader:Cache-Control: no-cache, must-revalidate,
[rule: 31] action: break:404 Not Found,
*** end of the internal routing table ***,
dir() to /opt/taiga-back,
your memory page size is 4096 bytes,
detected max file descriptor number: 1048576,
building mime-types dictionary from file /etc/mime.types...1183 entry found,
lock engine: pthread robust mutexes,
thunder lock: disabled (you can enable it with --thunder-lock),
bind(): Permission denied [core/socket.c line 230],```

**Comment by lubo** [comment]
Hi. I don't think `~` is a valid value for `UWSGI_HTTP`. See [uWSGI Options](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#http).

**Comment by Sawrz** [comment]
In your [docker-compose file](https://github.com/devinsolutions/docker-taiga/blob/master/docker-compose.advanced.yml) you use ~. Maybe it's worth to change it there?

However, I removed the `UWSGI_HTTP` environment parameter entirely, but I get the same error message as before.

**Comment by lubo** [comment]
In YAML, `~` is equivalent to `null`. So, `UWSGI_HTTP: ~` just unsets `UWSGI_HTTP`. Could you provide your whole compose file?

**Comment by Sawrz** [comment]
Ah ok! I didn't knew that. The thing is I moved from docker compose to portainer. Unfortunately they support docker-compose only on version 2. 
So I had to translate my old compose file to docker. [Here](https://i.imgur.com/ZqSLNU8.png) you'll find the configuration overview.

I used a combination of my docker-compose file and the updates you made within the last 3 monts. The content:
```
version: "3.7"

x-taiga-common: &taiga-common
  image: devinsolutions/taiga:5.0.10
  volumes:
    - type: bind
      source: /share/cloud_services/taiga/media
      target: /srv/taiga-back/media
    - /share/Containers/config_templates/taiga/front.json:/etc/opt/taiga-front/conf.json:ro
    - /share/Containers/config_templates/taiga/settings.py:/etc/opt/taiga-back/settings.py:ro
services:

  broker:
    image: rabbitmq:3.8
    environment:
      RABBITMQ_DEFAULT_VHOST: taiga
      RABBITMQ_NODENAME: rabbit@localhost
    volumes:
      - broker:/var/lib/rabbitmq
    networks:
      - backend

  database:
    image: postgres:11
    environment:
      POSTGRES_DB: DB_NAME
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_USER: USER
    stop_signal: SIGINT
    volumes:
      - type: bind
        source: /share/cloud_services/taiga/db
        target: /var/lib/postgresql/data
    networks:
      - backend

  events:
    image: devinsolutions/taiga-events:latest
    deploy:
      replicas: 1
      update_config:
        order: start-first
    healthcheck:
      interval: 5s
      # Taiga-events seems unable to reconnect to message broker when connection cannot be
      # established or is closed. There also does not seem to be another way to tell if the server
      # is actually able to communicate with the broker.
      test: "wget -q -t 1 http://localhost:8080 2>&1 | grep -q '426 Upgrade Required' &&
        ! egrep -m 1 -q '^Unhandled rejection ' /var/log/taiga-events.log"
    volumes:
      - /share/Containers/config_templates/taiga/events.json:/etc/opt/taiga-events/config.json:ro
    networks:
      - backend

  migrations:
    <<: *taiga-common
    command:
      - migrate
      # Make sure this command is run only during the initial setup as it will
      # overwrite existing data.
      # - populate-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - backend


    

  server:
    <<: *taiga-common
    command: run-server
    deploy:
      replicas: 1
      update_config:
        order: start-first
    environment:
      UWSGI_HTTP: ~
      UWSGI_HTTP_SOCKET: :8080
      UWSGI_OFFLOAD_THREADS: 4
      UWSGI_UWSGI_SOCKET: :3031
    healthcheck:
      test: wget -q -t 1 --spider http://localhost:8080/api/v1/
    stop_signal: SIGHUP
    environment:
      - VIRTUAL_HOST= URL
      - LETSENCRYPT_HOST= URL
    networks:
      - backend
      - reverse_proxy

volumes:
  broker:

networks:
  backend:
    name: taiga_backend
  reverse_proxy:
    external: true
```
