### ISSUE TITLE
Oops somethin happened! You're changes weren't saved.

### ISSUE THREAD

**Issue by juic3pow3rs** [devinsolutions/docker-taiga#9]
I get that error almost everytime I create or edit something within a project doesn't matter if it's a User Story, a Task or an EPIC.

Interestingly all the changes I execute get saved even though I get that error notification.

Any idea why this happens?

- error.log is empty

- docker-compose:
```
version: "3.2"

services:
  database:
    image: postgres:alpine
    container_name: taiga-db
    stop_signal: SIGINT
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - "5432"
  server:
    image: devinsolutions/taiga:latest
    container_name: taiga
    depends_on:
      - database
    command:
      - run-server
    healthcheck:
      test: wget -q -t 1 --spider http://localhost:8080/api/v1/
    expose:
      - "8080"
    stop_signal: SIGHUP
    volumes:
      - ./data/media:/srv/taiga-back/media
      - ./conf/settings.py:/etc/opt/taiga-back/settings.py:ro
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=reverse-proxy"
      # Entrypoint and TLS
      - "traefik.http.routers.taiga.entrypoints=https"
      - "traefik.http.routers.taiga.rule=Host(`taiga.domain.org`)"
      - "traefik.http.routers.taiga.tls.options=myTLSOptions@file"
      - "traefik.http.routers.taiga.tls.certresolver=le"
      # Middlewares:
      - "traefik.http.routers.taiga.middlewares=taiga@docker"
      # Middleware taiga adds additional headers:
      - "traefik.http.middlewares.taiga.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.taiga.headers.framedeny=true"
      - "traefik.http.middlewares.taiga.headers.sslredirect=true"
      - "traefik.http.middlewares.taiga.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.taiga.headers.stsPreload=true"
      - "traefik.http.middlewares.taiga.headers.stsSeconds=15552000"

networks:
    default:
       external:
         name: reverse-proxy
```

- settingy.py:
```
SECRET_KEY = '<secret>'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'taiga.domain.org',
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '<dbname>',
        'USER': '<dbuser>',
        'PASSWORD': '<dbuserpass>',
        'HOST': 'database',
        'PORT': '5432',
    }
}

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://guest:guest@broker/taiga"}
```
